# Euler Project 2: Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#   
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibo_n <- function(numbers, init = c(1,2)) {
  for (i in 1:(numbers-2)) {
    next_index <- length(init)
    init[next_index+1] <- init[next_index-1] + init[next_index]
  }
  return(init)
}

even_num_less_4_mil <- function(value) {
  if (value %% 2 == 0 & value < 4000000) {
    return(T)
  } else {
    return(F)
  }
}

sum(Filter(even_num_less_4_mil, fibo_n(50)))

